name: expense_manager
description: A Flutter app to manage and track expenses.
publish_to: 'none' # Prevent accidental publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.3
  uuid: ^4.4.0
  cupertino_icons: ^1.0.8
  path_provider: ^2.1.2
  csv: ^6.0.0
  pdf: ^3.10.7
  fl_chart: ^0.70.0
  intl: ^0.19.0  
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
